<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRpruK7b\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRpruK7b/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRpruK7b.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRpruK7b\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRpruK7b\App_KernelDevDebugContainer([
    'container.build_hash' => 'RpruK7b',
    'container.build_id' => '38e7f8ce',
    'container.build_time' => 1734283811,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRpruK7b');
